pipeline {
    agent any

    tools {
        maven "MAVEN"
        jdk "JDK"
    }


        stage('Build') {
            steps {
                dir("/var/lib/jenkins/workspace/demopipelinetask/jenkins-pipeline-example/my-app/") {
                sh 'mvn -B -DskipTests clean package'
                }
            
            }
        }
     }
    post {
       always {
          junit(
        allowEmptyResults: true,
        testResults: '*/test-reports/.xml'
      )
      }
   } 
}
